from datetime import date, timedelta


def generate_demo_rows():
    """Return realistic demo records for preview mode."""
    today = date.today()
    base = today - timedelta(days=7)

    return [
        {
            "sc_name": "tchinchen",
            "team": "EMEA",
            "date": str(base + timedelta(days=0)),
            "time": "09:00:00",
            "account": "acme",
            "event_type": "demo",
            "duration": 45,
            "pd_accepted": "accepted",
            "customer_attended": "Customer Confirmed",
            "is_recurring": False,
            "location": "Remote",
            "address": "",
            "pd_count": 2,
            "pd_attendees": ["tchinchen", "another03"],
            "summary": "Acme platform demo",
        },
        {
            "sc_name": "another01",
            "team": "AMER",
            "date": str(base + timedelta(days=1)),
            "time": "11:30:00",
            "account": "contoso",
            "event_type": "workshop",
            "duration": 60,
            "pd_accepted": "accepted",
            "customer_attended": "Customer Confirmed",
            "is_recurring": False,
            "location": "Onsite",
            "address": "Contoso HQ",
            "pd_count": 1,
            "pd_attendees": ["another01"],
            "summary": "Contoso architecture workshop",
        },
        {
            "sc_name": "another02",
            "team": "AMER",
            "date": str(base + timedelta(days=2)),
            "time": "15:00:00",
            "account": "fabrikam",
            "event_type": "tech sync",
            "duration": 30,
            "pd_accepted": "accepted",
            "customer_attended": "Customer Not Confirmed",
            "is_recurring": True,
            "location": "Remote",
            "address": "",
            "pd_count": 2,
            "pd_attendees": ["another02", "tchinchen"],
            "summary": "Weekly technical sync",
        },
        {
            "sc_name": "another03",
            "team": "APAC",
            "date": str(base + timedelta(days=3)),
            "time": "08:00:00",
            "account": "globex",
            "event_type": "pov kick-off",
            "duration": 50,
            "pd_accepted": "accepted",
            "customer_attended": "Customer Confirmed",
            "is_recurring": False,
            "location": "Remote",
            "address": "",
            "pd_count": 1,
            "pd_attendees": ["another03"],
            "summary": "POV kickoff and scoping",
        },
        {
            "sc_name": "tchinchen",
            "team": "EMEA",
            "date": str(base + timedelta(days=4)),
            "time": "13:00:00",
            "account": "initech",
            "event_type": "qbr",
            "duration": 40,
            "pd_accepted": "accepted",
            "customer_attended": "Customer Confirmed",
            "is_recurring": False,
            "location": "Remote",
            "address": "",
            "pd_count": 2,
            "pd_attendees": ["tchinchen", "another01"],
            "summary": "Initech QBR",
        },
    ]
